<?php

/**
 * 定义网站程序数据表
 *
 * @author      mason X<83213956@qq.com>
 * @version     2.0.0
 *
 **/

# 定义网站程序所用的表格前缀
define('PREFIX', 'X_TEAM_');

# 定义网站程序所用的数据表名
define('X_TEAM_ACCOUNT', PREFIX.'ACCOUNT');
define('X_TEAM_ADMIN', PREFIX.'ADMIN');
define('X_TEAM_COMBINE_SERVER', PREFIX.'COMBINE_SERVER');
define('X_TEAM_BANS', PREFIX.'BANS');
define('X_TEAM_BAN_LOG', PREFIX.'BAN_LOG');
define('X_TEAM_BLOCKED_IP', PREFIX.'BLOCKED_IP');
define('X_TEAM_CREDITS_CONFIG', PREFIX.'CREDITS_CONFIG');
define('X_TEAM_CREDITS_LOGS', PREFIX.'CREDITS_LOGS');
define('X_TEAM_CRON', PREFIX.'CRON');
define('X_TEAM_DOWNLOADS', PREFIX.'DOWNLOADS');
define('X_TEAM_FLA', PREFIX.'FLA');
define('X_TEAM_NEWS', PREFIX.'NEWS');
define('X_TEAM_PASSCHANGE_REQUEST', PREFIX.'PASSCHANGE_REQUEST');
define('X_TEAM_PLUGINS', PREFIX.'PLUGINS');
define('X_TEAM_REGISTER_ACCOUNT', PREFIX.'REGISTER_ACCOUNT');
define('X_TEAM_VOTES', PREFIX.'VOTES');
define('X_TEAM_VOTE_LOGS', PREFIX.'VOTE_LOGS');
define('X_TEAM_VOTE_SITES', PREFIX.'VOTE_SITES');
define('X_TEAM_NEWS_TRANSLATIONS', PREFIX.'NEWS_TRANSLATIONS');
define('X_TEAM_TOAST', PREFIX.'TOAST');